### ISSUE TITLE
Usage of the dynamic home page with components that require child elements is unclear

### ISSUE THREAD

**Issue by aboukhal** [redhat-developer/rhdh-plugins#597]
I have tried to adjust the Dynamic Home Page through mountPoints. This works well for the standard use cases documented in this repository and the official Red Hat documentation. However, upon trying my hand with a more complex scenario, I'm unsure if I encountered an area where the implementation does not support the use case or whether the documentation could be improved to help users get things right.

Example:

```
dynamicPlugins:
  frontend:
    red-hat-developer-hub.backstage-plugin-dynamic-home-page:
      dynamicRoutes:
        - path: /
          importName: DynamicHomePage
      mountPoints:
        - mountPoint: home.page/cards
          importName: TabbedCard
          config:
            layouts:
              xl: { w:7, h: 8 }
              [...]
        [...]
```

Expectation: An empty, unconfigured component appears - or at least the space is blocked in the layout

Actual: Only the following components are rendered. The TabbedCard does not appear, not even in the HTML code.

Is it even possible to use a TabbedCard with the DynamicHomePage? If so, would it be possible to add an example to the documentation on how to work with components that take children?

**Comment by christoph-jerolimov** [comment]
Hello @aboukhal,

thanks for sharing your feedback. The home page plugin currently does not have a "TabbedCard" component. The mountPoint `importName` needs to reference a React component that is exported by the plugin.

Other dynamic plugins, even custom ones, can add "cards" (or other components) to the home page this way. But the set of default cards is currently limited to this set: https://github.com/redhat-developer/rhdh-plugins/tree/main/workspaces/homepage/docs/cards

Mount points that reference an invalid `importName` are ignored, that's the reason why you don't see that space blocked or a empty "div" in the HTML code. You should see a warning in your browser log that says something like "TabbedCard not found in PluginRoot of red-hat-developer-hub.backstage-plugin-dynamic-home-page".

When you are a Red Hat Developer Hub customer please share your feedback and needs via our official support channels so that we can address these needs in the future.

**Comment by christoph-jerolimov** [comment]
Btw, we're open to contributions if you feel comfortable to add additional features.

When you calling it "TabbedCard" I expect that you want show multiple cards at the same spot and having a TabBar to switch back and forth between them? So this "TabbedCard" would again needs some childs like this, or?

```yaml
dynamicPlugins:
  frontend:
    red-hat-developer-hub.backstage-plugin-dynamic-home-page:
      dynamicRoutes:
        - path: /
          importName: DynamicHomePage
      mountPoints:
        - mountPoint: home.page/cards
          importName: TabbedCard
          config:
            tabId: ABC
            layouts:
              xl: { w:7, h: 8 }
              [...]
        [...]

        - mountPoint: home.page/tabbedcard
          importName: MarkdownContent
          config:
            tabId: ABC # TabbedCard pick up this card based on the same tabId ?! hmmm
            tabTitle: Tab 1
            content: "## Markdown content"
        - mountPoint: home.page/cards
          importName: MarkdownContent
          config:
            tabId: ABC
            tabTitle: Tab 2
            content: "## Another Markdown content"
```

Actually... this shows that such a "TabbedCard" (if someone would implement it) would also need some new content components to now show the card border twice... 🤔
